# Generated by Django 2.1 on 2020-02-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codequestion',
            name='vid',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
