# Generated by Django 2.0.12 on 2019-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(help_text='Enter the question text that you want displayed', max_length=1000, verbose_name='Question'),
        ),
    ]
