# Generated by Django 2.0.12 on 2019-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_supervisedregistrationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprofile',
            name='test',
            field=models.CharField(default='boom', max_length=10),
        ),
    ]
