# Generated by Django 2.0.12 on 2019-09-21 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, help_text='Enter the answer text that                                             you want displayed', max_length=1000, verbose_name='Content')),
                ('correct', models.BooleanField(default=False, help_text='Is this a correct answer?', verbose_name='Correct')),
            ],
            options={
                'verbose_name': 'DD Answer',
                'verbose_name_plural': 'DD Answers',
            },
        ),
        migrations.CreateModel(
            name='DDQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
                ('answer_order', models.CharField(blank=True, choices=[('content', 'Content'), ('none', 'None')], help_text='The order in which multichoice                     answer options are displayed                     to the user', max_length=30, null=True, verbose_name='Answer Order')),
                ('qtype', models.CharField(default='ddq', max_length=10)),
                ('step1', models.ImageField(upload_to='snips/')),
                ('step2', models.ImageField(upload_to='snips/')),
                ('step3', models.ImageField(upload_to='snips/')),
                ('step4', models.ImageField(upload_to='snips/')),
                ('step5', models.ImageField(upload_to='snips/')),
                ('step6', models.ImageField(upload_to='snips/')),
                ('step7', models.ImageField(upload_to='snips/')),
                ('step8', models.ImageField(upload_to='snips/')),
            ],
            options={
                'verbose_name': 'Drag Drop Question',
                'verbose_name_plural': 'Drag Drop Questions',
            },
            bases=('quiz.question',),
        ),
        migrations.AddField(
            model_name='ddanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddq.DDQuestion', verbose_name='Question'),
        ),
    ]
