# Generated by Django 2.0.12 on 2019-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddquestion',
            name='step1',
            field=models.ImageField(blank=True, null=True, upload_to='snips/'),
        ),
        migrations.AlterField(
            model_name='ddquestion',
            name='step2',
            field=models.ImageField(blank=True, null=True, upload_to='snips/'),
        ),
        migrations.AlterField(
            model_name='ddquestion',
            name='step3',
            field=models.ImageField(blank=True, null=True, upload_to='snips/'),
        ),
        migrations.AlterField(
            model_name='ddquestion',
            name='step4',
            field=models.ImageField(blank=True, null=True, upload_to='snips/'),
        ),
        migrations.AlterField(
            model_name='ddquestion',
            name='step5',
            field=models.ImageField(blank=True, null=True, upload_to='snips/'),
        ),
        migrations.AlterField(
            model_name='ddquestion',
            name='step6',
            field=models.ImageField(blank=True, null=True, upload_to='snips/'),
        ),
        migrations.AlterField(
            model_name='ddquestion',
            name='step7',
            field=models.ImageField(blank=True, null=True, upload_to='snips/'),
        ),
        migrations.AlterField(
            model_name='ddquestion',
            name='step8',
            field=models.ImageField(blank=True, null=True, upload_to='snips/'),
        ),
    ]
