# Generated by Django 2.0.12 on 2019-10-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay_Question',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
                ('qtype', models.CharField(default='essay', max_length=10)),
            ],
            options={
                'verbose_name': 'Essay question',
                'verbose_name_plural': 'Essay questions',
            },
            bases=('quiz.question',),
        ),
    ]
