# Generated by Django 2.0.12 on 2019-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0002_essayanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayanswer',
            name='evaluate',
            field=models.CharField(default='0.91', max_length=5),
        ),
    ]
